# This library is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this library; if not, see <http://www.gnu.org/licenses/>.


"""
Faux RPM -- lookalike rpm package which does nothing

:author: Christopher O'Brien <obriencj@preoccupied.net>
:license: GPL v3
"""


from ._rpm import ts as TransactionSetCore


class TransactionSet(TransactionSetCore):
    def setVSFlags(self, flags): ...
    def getVSFlags(self): ...
    def setVfyFlags(self, flags): ...
    def getVfyFlags(self): ...
    def getVfyLevel(self): ...
    def setVfyLevel(self, flags): ...
    def setColor(self, color): ...
    def setPrefColor(self, color): ...
    def setFlags(self, flags): ...
    def setProbFilter(self, ignoreSet): ...
    def parseSpec(self, specfile): ...
    def getKeys(self): ...
    def addInstall(self, item, key, how: str = ...) -> None: ...
    def addReinstall(self, item, key) -> None: ...
    def addErase(self, item) -> None: ...
    def addRestore(self, item) -> None: ...
    def run(self, callback, data): ...
    def check(self, *args, **kwds): ...
    def hdrCheck(self, blob) -> None: ...
    def hdrFromFdno(self, fd): ...


# The end.
